# Generated by Django 3.0.3 on 2020-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='basic',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
